<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT config (versioning?, categories?, topics?, breaking.changes?)>
<!ATTLIST config version (1 | 2) #REQUIRED>

<!ELEMENT versioning (rule+)>

<!ELEMENT rule (filename, version)>
<!ATTLIST rule name CDATA #IMPLIED>

<!ELEMENT filename EMPTY>
<!ATTLIST filename regex CDATA #REQUIRED>

<!ELEMENT version EMPTY>
<!ATTLIST version regex CDATA #REQUIRED>

<!ELEMENT categories (category*)>
<!ELEMENT category (#PCDATA)>
<!ATTLIST category name CDATA #REQUIRED>

<!ELEMENT topics (entry*)>
<!ELEMENT breaking.changes (entry*)>

<!ELEMENT entry (#PCDATA)>