<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
           vc:minVersion="1.1">
    <!-- Root Element -->
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="versioning" type="VersioningType" minOccurs="0" />
                <xs:element name="categories" type="CategoriesType" minOccurs="0" />
                <xs:element name="components" type="ComponentsType" minOccurs="0" />
                <xs:element name="topics" type="TopicsType" minOccurs="0" />
                <xs:element name="breaking.changes" type="BreakingChangesType" minOccurs="0" />
            </xs:sequence>
            <xs:attribute name="version" type="xs:string" fixed="4" use="required" />

            <xs:anyAttribute namespace="http://www.w3.org/2001/XMLSchema-instance" processContents="skip"/>
        </xs:complexType>
    </xs:element>

    <!-- Versioning -->
    <xs:complexType name="VersioningType">
        <xs:sequence>
            <xs:element name="rule" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="filename">
                            <xs:complexType>
                                <xs:attribute name="regex" type="xs:string" use="required"/>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="version">
                            <xs:complexType>
                                <xs:attribute name="regex" type="xs:string" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="name" type="xs:string"/>
                </xs:complexType>
            </xs:element>

            <xs:element name="phases">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="phase" type="PhaseType" minOccurs="1" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PhaseType">
        <xs:sequence>
            <xs:element name="next" type="xs:string"/>
            <xs:element name="prefix" type="xs:string" minOccurs="0"/>
            <xs:element name="suffix" type="xs:string" minOccurs="0"/>
            <xs:element name="formatter" type="xs:string"/>
            <xs:element name="events" type="EventsType" minOccurs="0">
                <xs:unique name="uniqueEventTrigger">
                    <xs:selector xpath="event"/>
                    <xs:field xpath="@on"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="EventsType">
        <xs:sequence>
            <xs:element name="event" type="EventType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="EventTriggerType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="phase_entered"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="EventType">
        <xs:sequence>
            <xs:element name="major" type="xs:unsignedInt" minOccurs="0" maxOccurs="1"/>
            <xs:element name="minor" type="xs:unsignedInt" minOccurs="0" maxOccurs="1"/>
            <xs:element name="patch" type="xs:unsignedInt" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="on" type="EventTriggerType" use="required"/>
    </xs:complexType>

    <!-- Categories -->
    <xs:complexType name="CategoriesType">
        <xs:sequence>
            <xs:element name="category" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="name" type="xs:string" use="required" />
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <!-- Components (recursive) -->
    <xs:complexType name="ComponentsType">
        <xs:sequence>
            <xs:element name="component" type="ComponentType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ComponentType">
        <xs:sequence>
            <xs:element name="component" type="ComponentType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="name" type="xs:string" />
    </xs:complexType>

    <!-- Topics (recursive) -->
    <xs:complexType name="TopicsType">
        <xs:sequence>
            <xs:element name="topic" type="TopicType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TopicType">
        <xs:sequence>
            <xs:element name="component-ref" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="ref" type="xs:string" use="required" />
                </xs:complexType>
            </xs:element>
            <xs:element name="topic" type="TopicType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <!-- Breaking Changes -->
    <xs:complexType name="BreakingChangesType">
        <xs:sequence>
            <xs:element name="entry" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>